//
//  ViewController.swift
//  101283994LabTest1
//
//  Created by Tech on 2022-02-11.
//

import UIKit

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
    }

    @IBOutlet weak var num1: UILabel!
    
    @IBOutlet weak var num2: UILabel!
    
    @IBOutlet weak var num3: UILabel!
    
    @IBOutlet weak var num4: UILabel!
    
    @IBOutlet weak var num5: UILabel!
    
    @IBOutlet weak var num6: UILabel!
    
    @IBAction func drawButton(_ sender: Any) {
        
        var val1 : Int
        
        var val2 : Int
        
        var val3 : Int
        
        var val4 : Int
        
        var val5 : Int
        
        var val6 : Int
        
        val1 = randomNum()
        
        // The following lines of code ensure that there are no repeated numbers generated by the random number generator.
        
        val2 = randomNum()
        val3 = randomNum()
        val4 = randomNum()
        val5 = randomNum()
        val6 = randomNum()
        
        if(val2==val1 || val2==val3 || val2==val4 || val2==val5 || val2==val6){
            val2 = randomNum()
        }
        
        if(val3==val2 || val3==val1 || val3==val4 || val3==val5 || val3==val6){
            val3 = randomNum()
        }
        
        if(val4==val3 || val4==val2 || val4==val1 || val2==val5 || val2==val6){
            val4 = randomNum()
        }
        
        
        if(val5==val1 || val5==val2 || val5==val3 || val5==val4 || val5==val6){
            val5 = randomNum()
        }
        
        
        if(val6==val1 || val6==val2 || val6==val3 || val6==val4 || val6==val5){
            val6 = randomNum()
        }
        
        let string1 = String(val1)
        num1.text = string1
        
        let string2 = String(val2)
        num2.text = string2
        
        let string3 = String(val3)
        num3.text = string3
        
        let string4 = String(val4)
        num4.text = string4
        
        let string5 = String(val5)
        num5.text = string5
        
        let string6 = String(val6)
        num6.text = string6
    }
    
    @IBAction func clearButton(_ sender: Any) {
        num1.text = "N1"
        num2.text = "N2"
        num3.text = "N3"
        num4.text = "N4"
        num5.text = "N5"
        num6.text = "N6"
    }
    
    @IBOutlet weak var infoLabel: UILabel!
    
    func randomInt(max: Int) -> Int {
    let rand: Int = Int(arc4random())
    return (rand % max) + 1
    }
    
    func randomNum() -> Int {
    let max: Int = 65
    let random = randomInt(max: max)
    return random
    }
    
}

